---
- name: Disable unused network protocols
  hosts: all
  become: true
  
  tasks:
    - name: Disable IP forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: 0
        state: present

    - name: Disable ICMP redirects
      sysctl:
        name: net.ipv4.conf.all.accept_redirects
        value: 0
        state: present

    - name: Disable ICMP redirects for default route
      sysctl:
        name: net.ipv4.conf.default.accept_redirects
        value: 0
        state: present

    - name: Disable source routed packets
      sysctl:
        name: net.ipv4.conf.all.accept_source_route
        value: 0
        state: present

    - name: Disable source routed packets for default route
      sysctl:
        name: net.ipv4.conf.default.accept_source_route
        value: 0
        state: present

