---
- name: World writable directories
  hosts: all
  become: true

  tasks:

    - name: Find world writable directories
      command: find / -perm -0002 -a ! -perm 1000 -type d -print
      register: output
      changed_when: false

    - name: Remove world writable directories
      file:
        path: "{{ item }}"
        state: absent
      with_items: "{{ output.stdout_lines }}"
      when: item is not none

