---
- name: Ensure web server runs as non-root user
  hosts: all
  become: yes

  tasks:
    - name: Create web server user
      user:
        name: asc-user
        comment: "Web server user"
        shell: "/usr/sbin/nologin"
        system: yes

    - name: Set ownership of web server files
      file:
        path: "/var/www/html"
        owner: asc-user
        group: asc-user
        recurse: yes

