---
- name: Disable Nginx directory listing
  hosts: all
  become: true
  tasks:
    - name: Create empty index.html file
      file:
        path: /usr/share/nginx/html/index.html
        state: touch

