---
- name: Ensure nginx does not advertise the OS versions
  hosts: all
  become: true
  
  tasks:
  - name: Replace server_tokens line
    replace:
      path: /etc/nginx/nginx.conf
      regexp: '^( *)server_tokens .*;$'
      replace: '\1server_tokens off;'
    notify:
      - restart nginx

  handlers:
  - name: restart nginx
    service:
      name: nginx
      state: restarted

