- name: Set kernel tuning parameters
  hosts: all
  become: true

  tasks:
  - name: Disable IP forwarding
    sysctl:
      name: net.ipv4.ip_forward
      value: 0
      state: present
    register: result_ip_forward

  - name: Disable ICMP redirects
    sysctl:
      name: net.ipv4.conf.all.accept_redirects
      value: 0
      state: present
    register: result_icmp_redirects

  - name: Disable packet redirect sending
    sysctl:
      name: net.ipv4.conf.all.send_redirects
      value: 0
      state: present
    register: result_packet_redirects

  - name: Disable source routed packets
    sysctl:
      name: net.ipv4.conf.all.accept_source_route
      value: 0
      state: present
    register: result_source_routed_packets

  - name: Enable TCP SYN Cookies
    sysctl:
      name: net.ipv4.tcp_syncookies
      value: 1
      state: present
    register: result_tcp_syn_cookies

  - name: Ignore Broadcast Requests
    sysctl:
      name: net.ipv4.icmp_echo_ignore_broadcasts
      value: 1
      state: present
    register: result_ignore_broadcasts

  - name: Enable Bad Error Message Protection
    sysctl:
      name: net.ipv4.icmp_ignore_bogus_error_responses
      value: 1
      state: present
    register: result_bad_error_protection

  - name: Save sysctl.conf file
    copy:
      src: /etc/sysctl.conf
      dest: /etc/sysctl.conf
      owner: root
      group: root
      mode: '0644'
    when: result_ip_forward.changed or result_icmp_redirects.changed or result_packet_redirects.changed or result_source_routed_packets.changed or result_tcp_syn_cookies.changed or result_ignore_broadcasts.changed or result_bad_error_protection.changed

