---
- name: Update Ubuntu with latest security patches
  hosts: all
  become: true
  tasks:
  - name: Update Ubuntu
    apt:
      update_cache: yes
      upgrade: yes
      autoremove: yes

  - name: Disable automounting for CD/DVDs and USBs
    mount:
      path: /media
      src: none
      fstype: none
      opts: "noauto"
      state: present
      dump: "0"
      passno: "0"

  - name: Ensure that password is set for single user mode
    lineinfile:
      path: /etc/sysconfig/init
      regexp: '^SINGLE=/sbin/sulogin'
      line: 'SINGLE=/sbin/sulogin -p'
      state: present
      create: yes
      mode: '0644'
      backup: yes

- name: Configure stateful firewall rules on GCP Ubuntu VM
  hosts: all
  become: true
  tasks:
  - name: Set default firewall policy to deny
    ufw:
      default: deny
      state: enabled

  - name: Allow incoming traffic on port 22 (SSH)
    ufw:
      rule: allow
      port: 22

  - name: Allow incoming traffic on port 80 (HTTP)
    ufw:
      rule: allow
      port: 80

  - name: Allow incoming traffic on port 443 (HTTPS)
    ufw:
      rule: allow
      port: 443

  - name: Allow outgoing traffic
    ufw:
      direction: outgoing
      policy: allow

- name: Enable SELinux
  hosts: all
  become: true
  tasks:
  - name: Set SELinux policy to enforcing
    ansible.posix.selinux:
      policy: targeted
      state: enforcing

