- name: Install Fail2Ban
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Fail2Ban
      apt:
        name: fail2ban
        state: present
      notify: restart fail2ban

    - name: Copy Fail2Ban config file
      copy:
        src: ./fail2ban.conf
        dest: /etc/fail2ban/fail2ban.conf
        owner: root
        group: root
        mode: 0644
      notify: restart fail2ban

    - name: Copy Fail2Ban jail configuration file
      copy:
        src: ./jail.local
        dest: /etc/fail2ban/jail.local
        owner: root
        group: root
        mode: 0644
      notify: restart fail2ban

  handlers:
    - name: restart fail2ban
      service:
        name: fail2ban
        state: restarted

